### ISSUE TITLE
Misprint, not enough zeros in the constant

### ISSUE THREAD

**Issue by ilka1999** [anrieff/libcpuid#179]
https://github.com/anrieff/libcpuid/blob/3b0a1f7e5b10efb978cea4c5cb5b727ba1ef3655/libcpuid/cpuid_main.c#L728

**Comment by anrieff** [comment]
Fixed in d02c054.

Thanks for spotting this! Interestingly enough, this did not manifest itself, as the only piece where `ext` was used is for determining whether this CPU supports reading the brand string. Seems all our CPUs in the test database support it, so the if was always true even with the correct computation.
