### ISSUE TITLE
Wrong rdmsr temperature/voltage/clock for Core 2 CPUs

### ISSUE THREAD

**Issue by ocerman** [anrieff/libcpuid#185]
The rdmsr information from cpuid_tool is not correct for Intel Core 2 CPUs.

For the Core 2 Quad Q6600, the cpuid_tool is reporting:
```
  MSR.mperf  : 1 MHz
  MSR.aperf  : 4 MHz
  min. multi.: 9.00
  cur. multi.: 6.00
  temperature: -63 degrees Celsius
  core volt. : 0.28 Volts
  bus clock  : 343.57 MHz
```
The voltage should be ~ 1.2V, the bus clock ~ 266 MHz and the temperature ~ 40 °C.  Also min. multiplier should be 6.

rdmsr-raw:
```
vendor_str=GenuineIntel
brand_str=Intel(R) Core(TM)2 Quad CPU    Q6600  @ 2.40GHz
cpu_clock_measure=2405MHz
msr[0x0000e7]=00 00 00 82 4a e1 8f 82 
msr[0x0000e8]=00 00 00 72 90 e7 b4 4e 
msr[0x000198]=09 1e 09 1e 06 00 06 1e 
msr[0x00019c]=00 00 00 00 88 3e 00 00 
msr[0x00002a]=00 00 00 00 41 88 08 00 
msr[0x0001ad]=00 00 00 00 41 88 08 00 
msr[0x0001a2]=00 00 00 00 00 00 10 00 
msr[0x000198]=09 1e 09 1e 06 00 06 1e 
msr[0x0000ce]=00 14 09 1e 7f 7f 07 14 
```
[raw.txt](https://github.com/anrieff/libcpuid/files/10855017/raw.txt)
[report.txt](https://github.com/anrieff/libcpuid/files/10855018/report.txt)

**Comment by anrieff** [comment]
Thank you for reporting this.
The RAW MSR dump shows worrying things, e.g. the min multiplier is clearly stated as 9, in reg 0x0ce. But as I see the docs, the number there may be MHz*100, not multiplier. What is the idle frequency (at min multiplier), can you test?
By multiplier 6 it would be 1600 MHz, which I see as rather high, but possible.

We definitely don't decode IA32_PERF_STATUS (0x198) properly. The 0x06 0x1e there is undocumented ("model-specific, do not assume anything"), and our comment there is "the high byte seems to be the multiplier, the low byte is 0". This probably looked right on another CPU, but it's not correct. If [this](https://lwn.net/Articles/36664/) decoding can be trusted it, the 0x06 0x1e would mean "600 MHz, 1.18V", so at least the voltage seems correct.

The temperature computation is wrong because MSR_TEMPERATURE_TARGET (0x1a2) is basically empty - the thermal trip temperature is read as 0°C, instead of a reasonable value like 100°C. If it were 100°C, then the computation would be close to correct (37°C or 42°C, depending on whether TCC is 100 or 105°C).

**Comment by TheTumultuousUnicornOfDarkness** [comment]
I added checks in ac57f692759b35373c79baf7d8c9c7b77e12c519: it will not read unsupported MSR anymore.
