### ISSUE TITLE
Is Windows on arm64 supported?

### ISSUE THREAD

**Issue by DrakkLord** [anrieff/libcpuid#201]
Seen #96 about arm64 support, linux was mentioned quite a few times, I tried to build on arm64 windows and it didn't work, my question is is it supported, is it supposed to build? In the readme it just says that arm64 is supported but no OS is mentioned.

**Comment by TheTumultuousUnicornOfDarkness** [comment]
ARM support is WIP, please be patient. I try to add updates in #96 to inform about the progression.
I will update the wiki with more information once AArch32 support will be fully ready.

I cannot build libcpuid on Windows ARM64, I do not have an ARM machine running Windows. I have no idea if the kernel traps MRS intructions on Windows.
Anyway, a kernel driver will be required (like the x86 MSR driver), but the kernel interface is not fully ready. I focus on Linux and FreeBSD because I can run then on an emulated ARM CPU by using QEMU, but I will try to work on macOS and Windows support later.

> I tried to build on arm64 windows and it didn't work

Can you provide more details, like logs?

**Comment by TheTumultuousUnicornOfDarkness** [comment]
> if I try to make the asm inline then it doesn't work again because MSVC complains that it's not supported.

Ah, yes, I remember reading that inline assembly is not supported on 64-bit Windows. The problem is the way of MRC/MRS instruction work: it is not possible to "variabilize" the register name, so the full instruction is required during build time, and I do not know how to replace the `cpu_exec_mrs()` macro for Windows yet.

Any contribution is welcomed (especially for macOS and Windows support on ARM), I will try to commit and push the IOCTL interface today.

**Comment by DrakkLord** [comment]
I'm trying hard to understand what's going on with my setup, first off it seemed that I had build tools v141 installed instead of v143 which it should be since it's the latest, I've checked that the ml64.exe ( MASM ) works in the build tools so the issue I'm getting that it's not supported is bogus it's there and it works, so it turns out that it's a cmake issue since it finds the x64 assembler fine

    -- The ASM_MASM compiler identification is MSVC
    -- Found assembler: C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.40.33807/bin/Hostx64/x64/ml64.exe

however on arm64 it just refuses to find it hence the build time error of not being supported:

    -- The ASM_MASM compiler identification is unknown

What I would most likely contribute is at least a skeleton that can be used to build upon, I just want to use the library as is I could even live with the fact that it may fail to detect some things runtime for now, but just want to make sure it builds, so I will look into it, it's rather strange that the assembler is there in the built tools but compile time I get not supported error.

**Comment by TheTumultuousUnicornOfDarkness** [comment]
I think I fixed the issue in 6e6b4bcbf597cacdaf61720b626a4a45aa40949d.
Please reopen if you are still facing issues on Windows ARM64.

**Comment by TheTumultuousUnicornOfDarkness** [comment]
> In the readme it just says that arm64 is supported but no OS is mentioned.

I updated the README in 4df61a58b2ae8977d58a94010aa6bf9f24c15672.
