### ISSUE TITLE
No releases?

### ISSUE THREAD

**Issue by ShyPixie** [anrieff/libcpuid#23]
I'm maintaining a Gentoo overlay with libcpuid package (git version). I don't find any release, and this forces me to mask the package. Why no releases?

**Comment by anrieff** [comment]
Hi,
the reason there are no releases is that updates to libcpuid mostly contribute to the database of recognizable CPUs. Users are advised to check out the latest master, as this represents a stable version of the software - no major unstable features are in the making in master.
If you want, I will glorify the current version in master (probably tomorrow, since I want to merge a pull request first) as a "v. 0.2.2".

**Comment by ShyPixie** [comment]
You cannot create a tag mark? Then I could pull it from the tag. Users know they can download a git version, but I think that all software must have a release, otherwise things get out of control. I cannot have much control of what you do in git through a package, and as a result users will not know when they should compile the package again (because has no version bump).

**Comment by anrieff** [comment]
Whether the git master is usable depends mostly on maintenance policy. If all new features are developed in branches and are fully debugged before being merged to master, then everything in master is release-grade.
I have to admit, though, that I haven't adhered to this policy strictly, and relied on commit log messages to indicate unstable stages. For this reason, your comment about the need of releases is very reasonable. I have created a v0.2.1 release, and I will create a new one, v0.2.2 as soon as I merge in pull request #21.

**Comment by hartwork** [comment]
Hi!
Very cool to see that you want back to releases :clap: :smiley: 
Since pull request #22 has been merged by now: is master ready for 0.2.2?
Best, S

**Comment by anrieff** [comment]
Yes, I needed to verify a few things, which I did now. I updated the version to 0.2.2 wherever that was needed. Pushing a release in a moment.

**Comment by hartwork** [comment]
Thank you!
