### ISSUE TITLE
Information about the availability of SGX

### ISSUE THREAD

**Issue by eloaders** [anrieff/libcpuid#67]
You can add this?

i found code to do that.

`https://github.com/ayeks/SGX-hardware/blob/master/test-sgx.c`

**Comment by anrieff** [comment]
Yup. We'll need to bump library versions again, though, since this is not only a on/off flag - need to add fields to cpu_id_t and cpu_raw_data_t.

**Comment by anrieff** [comment]
Support added in the mentioned commit; I will test it thoroughly later and close the issue when I verify this is working.

**Comment by eloaders** [comment]
Ok, thank you very much.

**Comment by shirishag75** [comment]
please let us know how to test it as well, as cpuid_tool --report does not tell if I have a cpu which has sgx or not.

**Comment by anrieff** [comment]
SGX is only available on newer CPUs and BIOSes, as outlined [here](https://github.com/ayeks/SGX-hardware/blob/master/README.md). If you don't have SGX support (either because your CPU is not Skylake, or because you don't have a compliant BIOS, or it opted out of this feature), `cpuid_tool --report` will simply not list `sgx` in its features field.
In the case you have support, you need the `--sgx` option to decode the SGX leaf data. You can run it now as well, but it will simply say 'absent'. I'll document that more properly in a subsequent commit.

@eloaders, the Skylake machine I had in mind has a non-compliant BIOS, so the detection is still untested. I'll try with the Intel simulator.

**Comment by shirishag75** [comment]
thanx that worked, my issue is resolved :)

**Comment by anrieff** [comment]
Intel simulator doesn't emulate SGX support either.
But I made an artificial raw.txt using the data [here](https://github.com/ayeks/SGX-hardware/blob/master/README.md#sgx-is-available-for-your-cpu-and-enabled-in-bios), and it seems to decode everything correctly, so I'm closing the issue.
