### ISSUE TITLE
MSR decoding on Vishera (FX-8320E)

### ISSUE THREAD

**Issue by anrieff** [anrieff/libcpuid#91]
@X0rg, please take a look at this.
Here's what the latest libcpuid dumps with `cpuid_tool --rdmsr` on that machine:
```
 MSR.mperf  : 6 MHz
 MSR.aperf  : 21 MHz
 min. multi.: 14.00
 cur. multi.: 45.00
 max. multi.: 40.00
 core volt. : 1.16 Volts
 bus clock  : 100.33 MHz
```

The raw data is
```
CPU is AuthenticAMD AMD FX-8320E Eight-Core Processor              , stock clock is 4515MHz.
msr[0xc0010061]=00 00 00 00 00 00 00 40 
msr[0xc0010063]=00 00 00 00 00 00 00 00 
msr[0xc0010064]=80 00 01 7d 00 00 16 18 
msr[0xc0010065]=80 00 01 72 00 00 2e 13 
msr[0xc0010066]=80 00 01 5c 00 00 40 1d 
msr[0xc0010067]=00 00 01 5c 00 00 40 1d 
msr[0xc0010068]=00 00 01 5c 00 00 3e 1d 
msr[0xc0010069]=00 00 01 5c 00 00 40 1d 
msr[0xc001006a]=80 00 01 26 00 00 70 4c 
msr[0xc001006b]=00 00 00 00 00 00 00 00
```

~~The CPU multiplier and bus clock are correct: it is indeed 45x100.33 MHz.~~
The actual CPU voltage is 1.36.

**Comment by X0rg** [comment]
Are you sure CPU multipliers and bus block are correct? This is a 200MHz bus block on FX-8320E CPU-Z screenshots, like this:
[![](http://img.conseil-config.com/2014/12/AMD_FX_8320E_cpuz_oc.png)](http://img.conseil-config.com/2014/12/AMD_FX_8320E_cpuz_oc.png)

About the CPU Voltage, you are true: the Serial VID (SVI) Encodings are not the same for all families. In `get_info_voltage`, the formula `1.550 - 0.0125 * CpuVid` is used, but for 15h, it should be `1.5500 - 0.00625 * CpuVid` (giving 1,35625V instead of 1,1625V).

I will do a patch.

**Comment by anrieff** [comment]
Yes, you are right, the correct config is 200x22.5

**Comment by X0rg** [comment]
Well... If I understand, all CPUs before Ryzen work with a 200MHz bus speed (socket AM3 and AM3+).
APUs work with a 100MHz bus speed (socket FM2 and FM2+).
Since Zen platform (AM4), CPUs and APUs all work with a 100MHz bus speed.
Do you confirm?

Do you have any suggestion to detect if chip is a CPU or an APU (in `get_amd_multipliers()`)?

About CPU voltage, I'll check in all BKDG from K10 to K16.

**Comment by X0rg** [comment]
I recap my checks:
* 10h family:
  * Phenom: 200MHz
  * Athlon X2: 200MHz
  * Phenom II: 200MHz
  * Athlon II: 200MHz
  * Sempron: 200MHz  
**==> No changes needed**
* 11h family:
  * Turion X2: 200MHz
  * Turion II: 200MHz
**==> No changes needed**
* 12h family:
  * Sempron X2: 100MHz
  * Athlon II: 100MHz
  * E-Series: 100MHz
  * A-Series: 100MHz
**==> No changes needed**
* 14h family:
  * C-Series: 100MHz
  * E-Series: 100MHz
  * G-series: 100MHz (find only T56N screenshot)
  * Z-Series: unknown (I cannot find CPU-Z screenshot for Z-01 and Z-60)
**==> No changes needed**
* 15 family:
  * FX: 100MHz for Mobile APUs / 200MHz for Desktop
  * Athlon: 100MHz
  * A-Series: 100MHz
  * E-Series: 100MHz
**==> Changes required**
* 16h family:
  * Sempron: 100MHz
  * Athlon: 100MHz
  * A-Series: 100MHz
  * E-Series: 100MHz
**==> No changes needed**

FX-670K is a Richland APU with 100MHz bus clock; the associated code in recog_amd.c is `FUSION_A`. Same thing for FX-7500, and all FX APUs.
Idem for Athlon: APUs like Athlon 5370 are `FUSION_A`.
FX-8150 is a Zambezi (Bulldozer) CPU with a 200MHz bus clock, and his code is `NC`. Same thing for **FX-8320E**.
So, it seems to be correct to use `amd_code_t` to detect if chip is CPU or an APU. See 58b8eabd7c2b4d6e9d41b08983a90c9904c39e78.

**Comment by anrieff** [comment]
> Well... If I understand, all CPUs before Ryzen work with a 200MHz bus speed (socket AM3 and AM3+).
APUs work with a 100MHz bus speed (socket FM2 and FM2+).
Since Zen platform (AM4), CPUs and APUs all work with a 100MHz bus speed.
Do you confirm?

Yes, that's correct AFAIK.

> Do you have any suggestion to detect if chip is a CPU or an APU (in get_amd_multipliers())?

Yes, one way that may work is to look into the brand string and test if it contains part `" APU "`. E.g., on Llanos APUs, the brand string is something like `AMD A6-3670 APU with Radeon(tm) HD Graphics`. That could be used in conjunction with the current tests for amd_code_t, as it adds a very strong signal about the CPU being an APU. I've added this in a196e8d and 9866149, so the relevant line in get_amd_multipliers can become

```
const int is_apu = ((FUSION_C <= info->internal->code.amd) && (info->internal->code.amd <= FUSION_A))
                || (info->internal->bits & _APU_);
const int divisor = is_apu ? 1 : 2;
```

**Comment by X0rg** [comment]
Thank you for this change. Applied in dd702cd.
